"""filing_chunks (+ embedding/tsv) and the AI log + answer cache

Milestone 3: retrieval chunks with a pgvector embedding and a Postgres
GENERATED tsvector for hybrid search, plus ai_interactions (audit) and
answer_cache (per provider+model).

Hand-written (not autogenerated) so it only adds new tables and never touches
existing ones — same caution as 0002/0003. The special bits (vector column,
GENERATED tsvector, HNSW + GIN indexes) are emitted as raw SQL because Alembic's
table builder can't express them directly.

Revision ID: 0004
Revises: 0003
Create Date: 2026-06-18
"""
from typing import Sequence, Union

from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: Union[str, None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

EMBEDDING_DIM = 384  # BAAI/bge-small-en-v1.5


def upgrade() -> None:
    op.create_table(
        "filing_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filing_id", sa.Integer(), nullable=False),
        sa.Column("section_code", sa.String(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column("content_text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("embedding", Vector(EMBEDDING_DIM), nullable=True),
        sa.ForeignKeyConstraint(["filing_id"], ["filings.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "filing_id", "chunk_index", name="uq_chunks_filing_index"
        ),
    )
    op.create_index(
        op.f("ix_filing_chunks_filing_id"), "filing_chunks", ["filing_id"]
    )
    op.create_index(
        op.f("ix_filing_chunks_content_hash"), "filing_chunks", ["content_hash"]
    )

    # Keyword half of hybrid retrieval: a DB-maintained tsvector + GIN index.
    op.execute(
        "ALTER TABLE filing_chunks ADD COLUMN tsv tsvector "
        "GENERATED ALWAYS AS (to_tsvector('english', content_text)) STORED"
    )
    op.execute("CREATE INDEX ix_filing_chunks_tsv ON filing_chunks USING gin (tsv)")

    # Semantic half: HNSW with cosine ops (bge embeddings are cosine-normalized).
    op.execute(
        "CREATE INDEX ix_filing_chunks_embedding ON filing_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )

    op.create_table(
        "ai_interactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("filing_id", sa.Integer(), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("retrieved_chunk_ids", sa.JSON(), nullable=True),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("abstained", sa.Boolean(), nullable=True),
        sa.Column("cached", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("feedback", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["filing_id"], ["filings.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_interactions_filing_id"), "ai_interactions", ["filing_id"]
    )

    op.create_table(
        "answer_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filing_id", sa.Integer(), nullable=False),
        sa.Column("question_hash", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("retrieved_chunk_ids", sa.JSON(), nullable=True),
        sa.Column("abstained", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["filing_id"], ["filings.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "filing_id",
            "question_hash",
            "provider",
            "model",
            name="uq_answer_cache_key",
        ),
    )
    op.create_index(
        op.f("ix_answer_cache_filing_id"), "answer_cache", ["filing_id"]
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_answer_cache_filing_id"), table_name="answer_cache")
    op.drop_table("answer_cache")
    op.drop_index(
        op.f("ix_ai_interactions_filing_id"), table_name="ai_interactions"
    )
    op.drop_table("ai_interactions")
    op.execute("DROP INDEX IF EXISTS ix_filing_chunks_embedding")
    op.execute("DROP INDEX IF EXISTS ix_filing_chunks_tsv")
    op.drop_index(
        op.f("ix_filing_chunks_content_hash"), table_name="filing_chunks"
    )
    op.drop_index(op.f("ix_filing_chunks_filing_id"), table_name="filing_chunks")
    op.drop_table("filing_chunks")
